version: '3.8'

services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "love"
      MYSQL_DATABASE: "golang"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/_sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  mongo_data:
  mysql_data:
