// Code generated by MockGen. DO NOT EDIT.
// Source: sessions.go

// Package sessions is a generated GoMock package.
package sessions

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockSessionManagerInterface is a mock of SessionManagerInterface interface.
type MockSessionManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockSessionManagerInterfaceMockRecorder
}

// MockSessionManagerInterfaceMockRecorder is the mock recorder for MockSessionManagerInterface.
type MockSessionManagerInterfaceMockRecorder struct {
	mock *MockSessionManagerInterface
}

// NewMockSessionManagerInterface creates a new mock instance.
func NewMockSessionManagerInterface(ctrl *gomock.Controller) *MockSessionManagerInterface {
	mock := &MockSessionManagerInterface{ctrl: ctrl}
	mock.recorder = &MockSessionManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionManagerInterface) EXPECT() *MockSessionManagerInterfaceMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockSessionManagerInterface) Check(in *SessionID) *Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", in)
	ret0, _ := ret[0].(*Session)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockSessionManagerInterfaceMockRecorder) Check(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockSessionManagerInterface)(nil).Check), in)
}

// Create mocks base method.
func (m *MockSessionManagerInterface) Create(in *Session) (*SessionID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", in)
	ret0, _ := ret[0].(*SessionID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSessionManagerInterfaceMockRecorder) Create(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionManagerInterface)(nil).Create), in)
}
